target_machine:
  - x86_64
  - aarch64
  - powerpc64le
centos_machine:
  - x86_64
  - aarch64
  - ppc64le
cross_target_platform:
  - linux-64
  - linux-aarch64
  - linux-ppc64le
cdt_arch:
  - x86_64
  - aarch64
  - ppc64le

ctng_vendor:
  - conda
cdt_name:
  - cos7

zip_keys:
  - - target_machine
    - cross_target_platform
    - centos_machine
    - cdt_arch
