{% set use_amazon_linux = "yes" %}  # [cross_target_platform == "linux-aarch64"]
{% set use_amazon_linux = "no" %}  # [cross_target_platform != "linux-aarch64"]
{% if use_amazon_linux == "yes" %}
{% set distro = "amzn2" %}
{% set version = "2.26" %}
{% set version2 = "2.26-39" %}
{% else %}
{% set distro = "el7" %}
{% set version = "2.17" %}
{% set version2 = "2.17-317" %}
{% endif %}

{% if use_amazon_linux == "yes" %}
{% set kernel_headers_version = "4.14.214" %}
{% set kernel_headers_version2 = "4.14.214-160.339" %}
{% else %}
{% set kernel_headers_version = "4.18.0" %}
{% set kernel_headers_version2 = "4.18.0-1160" %}  # [cross_target_platform == "linux-64" or cross_target_platform == "linux-ppc64le"]
{% set kernel_headers_version2 = "4.18.0-193.28.1" %}  # [cross_target_platform == "linux-aarch64"]
{% set kernel_headers_version2 = "4.18.0-1127" %}  # [cross_target_platform == "linux-s390x"]
{% endif %}
{% set kernel_headers_version = "3.10.0" %}  # [cross_target_platform != "linux-aarch64"]

{% set build_number = "11" %}
{% set rpm_url = "http://mirror.centos.org/centos/7.9.2009/os/x86_64/Packages" %}  # [cross_target_platform == "linux-64"]
{% if use_amazon_linux == "yes" %}
{% set rpm_url = "https://graviton-rpms.s3.amazonaws.com/amzn2-core_2021_01_26/amzn2-core" %}  # [cross_target_platform == "linux-aarch64"]
{% else %}
{% set rpm_url = "http://mirror.centos.org/altarch/7/os/aarch64/Packages" %}       # [cross_target_platform == "linux-aarch64"]
{% endif %}
{% set rpm_url = "http://mirror.centos.org/altarch/7/os/ppc64le/Packages" %}       # [cross_target_platform == "linux-ppc64le"]
{% set rpm_url = "http://download.sinenomine.net/clefos/7/os/s390x" %}             # [cross_target_platform == "linux-s390x"]

package:
  name: linux-sysroot
  version: {{ version }}

source:
  - folder: binary
    no_hoist: True
    url: {{ rpm_url }}/glibc-{{ version2 }}.{{ distro }}.{{ centos_machine }}.rpm            # [cross_target_platform != "linux-s390x"]
    url: {{ rpm_url }}/glibc-{{ version2 }}.{{ distro }}.1.{{ centos_machine }}.rpm          # [cross_target_platform == "linux-s390x"]
    sha256: 49eb081de1ddd13f5440abdbb3b42cdd01d11b74d624793ae1b80a1cf432551b  # [cross_target_platform == "linux-64"]
{% if use_amazon_linux == "yes" %}
    sha256: 951f9895db88e559f50bb8e7cfe98b1293d002dd4fed2fcab1b6de3c0ccd66fc  # [cross_target_platform == "linux-aarch64"]
{% else %}
    sha256: ca1976545bcd4a6c099f1b3e2505469083b6bb4901d2517275a8da4138c0b21a  # [cross_target_platform == "linux-aarch64"]
{% endif %}
    sha256: f9ff840d0cd01cb900c5ae3a5ce0adb5d388be7a938dc83cdeb374d27fc0a68e  # [cross_target_platform == "linux-ppc64le"]
    sha256: c6ce1ac0472ec946cf7064e02caad113e4f348fdc1259161d5640dbdb295634b  # [cross_target_platform == "linux-s390x"]

  - folder: binary-glibc-common
    no_hoist: True
    url: {{ rpm_url }}/glibc-common-{{ version2 }}.{{ distro }}.{{ centos_machine }}.rpm     # [cross_target_platform != "linux-s390x"]
    url: {{ rpm_url }}/glibc-common-{{ version2 }}.{{ distro }}.1.{{ centos_machine }}.rpm   # [cross_target_platform == "linux-s390x"]
    sha256: e89e472b20c02c25fd69047abc7a0e7e3b1deeb4d5b88b17886318c8af8439d7  # [cross_target_platform == "linux-64"]
{% if use_amazon_linux == "yes" %}
    sha256: 5e9701f9b79a906493f665fd29a92f2220ea85a7b30a7653c217c2c7a88072d7  # [cross_target_platform == "linux-aarch64"]
{% else %}
    sha256: 07c274dd3bd53185d63cb960726175d001f912f272c32019462dbd78c05f7083  # [cross_target_platform == "linux-aarch64"]
{% endif %}
    sha256: b83d663f9822828bd52282c0e43523a266ad3646d76108e4e3a32e7cf25ac658  # [cross_target_platform == "linux-ppc64le"]
    sha256: e6a3796bf72bd92f31d7aefe0096009bfa8ab592e143362c3c1b73c2129f7bb3  # [cross_target_platform == "linux-s390x"]

  - folder: binary-glibc-devel
    no_hoist: True
    url: {{ rpm_url }}/glibc-devel-{{ version2 }}.{{ distro }}.{{ centos_machine }}.rpm      # [cross_target_platform != "linux-s390x"]
    url: {{ rpm_url }}/glibc-devel-{{ version2 }}.{{ distro }}.1.{{ centos_machine }}.rpm    # [cross_target_platform == "linux-s390x"]
    sha256: 57e04523b12c9aa5a0632cbfa2ff13e33f1ecec5e6bd0b609a77d9c24cebf8c4  # [cross_target_platform == "linux-64"]
{% if use_amazon_linux == "yes" %}
    sha256: b4b3c888c9b11510a477d00b36c91d031d2da916bf5fa8f459088a16df2e22d3  # [cross_target_platform == "linux-aarch64"]
{% else %}
    sha256: 458738f7b415fb73473725b6bef340234954e4eb00731cbf8aa1afad5ccd12f6  # [cross_target_platform == "linux-aarch64"]
{% endif %}

    sha256: 915b115a348dd14bad459287601bbd4c963c5e06d01217aafd343b7d3cccc10c  # [cross_target_platform == "linux-ppc64le"]
    sha256: 1f46ff3924c3d55de7647366a06653db791fe528b06a0be1b3ddd0bea91b752e  # [cross_target_platform == "linux-s390x"]

  - folder: binary-tzdata
    no_hoist: True
    url: http://mirror.centos.org/centos/7.9.2009/os/x86_64/Packages/tzdata-2020a-1.el7.noarch.rpm
    sha256: bc5c790c0a346bb20abbbd866e0c1cf664cec9c3e4d4e21dbfe32b32616257ba

  - folder: binary-glibc-headers
    no_hoist: True
    url: {{ rpm_url }}/glibc-headers-{{ version2 }}.{{ distro }}.{{ centos_machine }}.rpm    # [cross_target_platform != "linux-s390x"]
    url: {{ rpm_url }}/glibc-headers-{{ version2 }}.{{ distro }}.1.{{ centos_machine }}.rpm  # [cross_target_platform == "linux-s390x"]
    sha256: b7e4e19b362cbd73e09e6ee5eff3d70dbeb7cc2c702a927b8f646f324d4ec4a3  # [cross_target_platform == "linux-64"]
{% if use_amazon_linux == "yes" %}
    sha256: a89dc81eda7019fede38bea0145459ed744e609188bc3261bfc8f3a937c26633  # [cross_target_platform == "linux-aarch64"]
{% else %}
    sha256: 58a5802d026435b36d7080ea4943868a82fc41642a2b0e475239bd6aaa5882cd  # [cross_target_platform == "linux-aarch64"]
{% endif %}
    sha256: e1b7daaccec1eafa1fb7ead6c4c81bf9390b2b849e96e1d2498e1352c0254a67  # [cross_target_platform == "linux-ppc64le"]
    sha256: 034e49d09f864c3afcf007a991da5c89ee2106ebeb3bdcf8aca61fc4f5ad916d  # [cross_target_platform == "linux-s390x"]

  - folder: binary-kernel-headers
    no_hoist: True
    url: {{ rpm_url }}/kernel-headers-{{ kernel_headers_version2 }}.{{ distro }}.{{ centos_machine }}.rpm
    sha256: 81b4e4f401d2402736ceba4627eaafd5b615c2cc45aa4d4f941ea79562045139  # [cross_target_platform == "linux-64"]
{% if use_amazon_linux == "yes" %}
    sha256: 6dc942a32dae8a2a4579de2140741a8caaa7bbbac04e83f0b1226bb9ca909e91  # [cross_target_platform == "linux-aarch64"]
{% else %}
    sha256: 56fffc40800cd7c30830009c860f04c8dba1110a6271efd804a0bb01e0bdf8a4  # [cross_target_platform == "linux-aarch64"]
{% endif %}
    sha256: 6875ad8dbbf0cff85bf39bd2446ffb9e92de78e113496fba37fa5da9f10348b1  # [cross_target_platform == "linux-ppc64le"]
    sha256: b4bd26bbccab8028d903d250a7e599f77c7c5ea8b7137f96aecf998016799d93  # [cross_target_platform == "linux-s390x"]

  - folder: binary-freebl
    no_hoist: True
    url: {{ rpm_url }}/nss-softokn-freebl-3.44.0-8.el7_7.{{ centos_machine }}.rpm
    sha256: 9949831b67f6eb68dc9df6df3e4570bd5f9301de3c7d67c41512fcaaadb40da5  # [cross_target_platform == "linux-64"]
    sha256: 5a62051cc69e76ffa44291ed12464a3ce4a8224dbf829330739aae500f33b2b2  # [cross_target_platform == "linux-aarch64"]
    sha256: 01439cbf4297a341e31b425961bdafc251a4765e22035977ca459c939f949899  # [cross_target_platform == "linux-ppc64le"]
    sha256: 8c88f6be69f0d88ac91a577cfb507c879446d3950a19843927082bf0d660accf  # [cross_target_platform == "linux-s390x"]

build:
  number: {{ build_number }}
  noarch: generic
  missing_dso_whitelist:
    - '*'

outputs:
  - name: kernel-headers_{{ cross_target_platform }}
    version: {{ kernel_headers_version }}
    script: build-kernel-headers.sh
    build:
      noarch: generic
      binary_relocation: False
      detect_binary_files_with_prefix: False
    requirements:
{% if cross_target_platform == "linux-64" %}
      run:
        - _sysroot_{{ cross_target_platform }}_curr_repodata_hack 3.*
{% endif %}
      run_constrained:
        - sysroot_{{ cross_target_platform }} =={{ version }}
    test:
      commands:
        test -f $PREFIX/{{ target_machine }}-{{ ctng_vendor }}-linux-gnu/sysroot/usr/include/linux/version.h

{% if cross_target_platform == "linux-64" %}
  - name: _sysroot_{{ cross_target_platform }}_curr_repodata_hack
    version: 3
    build:
      noarch: generic
    test:
      commands:
        - echo "works!"
{% endif %}
  - name: sysroot_{{ cross_target_platform }}
    script: build-sysroot.sh
    build:
      noarch: generic
      binary_relocation: False
      detect_binary_files_with_prefix: False
{% if cross_target_platform == "linux-64" %}
      track_features:
        - sysroot_{{ cross_target_platform }}_{{ version }}
      run_exports:
        strong:
          - __glibc >={{ version }},<3.0.a0
{% endif %}
    requirements:
      run:
{% if cross_target_platform == "linux-64" %}
        - _sysroot_{{ cross_target_platform }}_curr_repodata_hack 3.*
{% endif %}
        - {{ pin_subpackage('kernel-headers_' ~ cross_target_platform, exact=True) }}
    test:
      commands:
        - test -f $PREFIX/{{ target_machine }}-conda-linux-gnu/sysroot/lib/libc.so.6
        - test -f $PREFIX/{{ target_machine }}-conda-linux-gnu/sysroot/sbin/ldconfig
        - test -f $PREFIX/{{ target_machine }}-conda-linux-gnu/sysroot/usr/lib/crt1.o  # [cross_target_platform != "linux-aarch64"]
        - test -f $PREFIX/{{ target_machine }}-conda-linux-gnu/sysroot/usr/lib64/crt1.o  # [cross_target_platform == "linux-aarch64"]
        - test -f $PREFIX/{{ target_machine }}-conda-linux-gnu/sysroot/usr/include/limits.h
        - test -f $PREFIX/{{ target_machine }}-conda-linux-gnu/sysroot/usr/include/gnu/stubs-64.h  # [cross_target_platform == "linux-64"]
        - test -f $PREFIX/{{ target_machine }}-conda-linux-gnu/sysroot/usr/include/gnu/stubs.h  # [cross_target_platform != "linux-64"]
        - test -d $PREFIX/{{ target_machine }}-conda-linux-gnu/sysroot/usr/share/locale
        - test -f $PREFIX/{{ target_machine }}-conda-linux-gnu/sysroot/usr/bin/ldd
        - test -f $PREFIX/{{ target_machine }}-{{ ctng_vendor }}-linux-gnu/sysroot/lib/libc.so.6

  - name: sysroot-{{ cdt_name }}-{{ cdt_arch }}
    build:
      noarch: generic
    requirements:
      run:
        - sysroot_{{ cross_target_platform }} =={{ version }}
    test:
      commands:
        - test -f $PREFIX/{{ target_machine }}-conda-linux-gnu/sysroot/lib/libc.so.6
        - test -f $PREFIX/{{ target_machine }}-conda-linux-gnu/sysroot/sbin/ldconfig
        - test -f $PREFIX/{{ target_machine }}-conda-linux-gnu/sysroot/usr/lib/crt1.o  # [cross_target_platform != "linux-aarch64"]
        - test -f $PREFIX/{{ target_machine }}-conda-linux-gnu/sysroot/usr/lib64/crt1.o  # [cross_target_platform == "linux-aarch64"]
        - test -f $PREFIX/{{ target_machine }}-conda-linux-gnu/sysroot/usr/include/limits.h
        - test -f $PREFIX/{{ target_machine }}-conda-linux-gnu/sysroot/usr/include/gnu/stubs-64.h  # [cross_target_platform == "linux-64"]
        - test -f $PREFIX/{{ target_machine }}-conda-linux-gnu/sysroot/usr/include/gnu/stubs.h  # [cross_target_platform != "linux-64"]
        - test -d $PREFIX/{{ target_machine }}-conda-linux-gnu/sysroot/usr/share/locale
        - test -f $PREFIX/{{ target_machine }}-conda-linux-gnu/sysroot/usr/bin/ldd
        - test -f $PREFIX/{{ target_machine }}-{{ ctng_vendor }}-linux-gnu/sysroot/lib/libc.so.6

about:
  home: http://sources.redhat.com/glibc/
  license: LGPL-2.0-or-later AND LGPL-2.0-or-later WITH exceptions AND GPL-2.0-or-later AND MPL-2.0
  license_family: GPL
  license_file: nss-license
  # other license files are packaged with source
  summary: "(CDT) The GNU libc libraries and header files for the Linux kernel for use by glibc"
  description: |
        The glibc package contains standard libraries which are used by multiple
        programs on the system. In order to save disk space and memory, as well as to
        make upgrading easier, common system code is kept in one place and shared
        between programs. This particular package contains the most important sets of
        shared libraries: the standard C library and the standard math library.
        Without these two libraries, a Linux system will not function.

        Kernel-headers includes the C header files that specify the interface between
        the Linux kernel and userspace libraries and programs.  The header files
        define structures and constants that are needed for building most standard
        programs and are also needed for rebuilding the glibc package.

extra:
  recipe-maintainers:
    - isuruf
    - scopatz
    - beckermr
    - mingwandroid
